// <auto-generated />
using System;
using ASP.NETCoreD03.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace dotNetSumMVCD04.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260730111136_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCoreD03.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "SD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mob"
                        },
                        new
                        {
                            Id = 4,
                            Name = "UX"
                        });
                });

            modelBuilder.Entity("ASP.NETCoreD03.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("DOB")
                        .HasColumnType("date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 26,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 1,
                            Name = "Ahmed",
                            Salary = 1234m
                        },
                        new
                        {
                            Id = 2,
                            Age = 36,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 2,
                            Name = "Mohamed",
                            Salary = 2234m
                        },
                        new
                        {
                            Id = 3,
                            Age = 46,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 3,
                            Name = "Sara",
                            Salary = 4234m
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 4,
                            Name = "Omar",
                            Salary = 5234m
                        },
                        new
                        {
                            Id = 5,
                            Age = 23,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 1,
                            Name = "Ali",
                            Salary = 6234m
                        },
                        new
                        {
                            Id = 6,
                            Age = 36,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 2,
                            Name = "Mai",
                            Salary = 7234m
                        },
                        new
                        {
                            Id = 7,
                            Age = 49,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 3,
                            Name = "Ramy",
                            Salary = 8234m
                        },
                        new
                        {
                            Id = 8,
                            Age = 18,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 4,
                            Name = "Hamada",
                            Salary = 9234m
                        },
                        new
                        {
                            Id = 9,
                            Age = 26,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 1,
                            Name = "Hatem",
                            Salary = 10234m
                        },
                        new
                        {
                            Id = 10,
                            Age = 25,
                            DOB = new DateOnly(1, 1, 1),
                            DepartmentId = 2,
                            Name = "Osama",
                            Salary = 17234m
                        });
                });

            modelBuilder.Entity("ASP.NETCoreD03.Models.Employee", b =>
                {
                    b.HasOne("ASP.NETCoreD03.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("ASP.NETCoreD03.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
