// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dotNetSumMVCD03.Data.Context;

#nullable disable

namespace dotNetSumMVCD03.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("dotNetSumMVCD03.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MAD"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UI"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SD"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cloud"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Network"
                        });
                });

            modelBuilder.Entity("dotNetSumMVCD03.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            DepartmentId = 1,
                            Name = "Aly Eldean",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            DepartmentId = 2,
                            Name = "Abdelrahman",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            DepartmentId = 3,
                            Name = "Medhat",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            DepartmentId = 4,
                            Name = "Nada",
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 5,
                            Age = 25,
                            DepartmentId = 5,
                            Name = "Julia",
                            Salary = 5000m
                        });
                });

            modelBuilder.Entity("dotNetSumMVCD03.Models.Employee", b =>
                {
                    b.HasOne("dotNetSumMVCD03.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("dotNetSumMVCD03.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
